name: dart_html5_canvas
version: 0.0.2
author: Matthew Butler & Steve Fulton and Jeff Fulton (O'Reilly)
description: Dart port of examples from HTML5 Canvas, 2nd Edition
homepage: https://github.com/butlermatt/dart_HTML5_Canvas
documentation: https://github.com/butlermatt/dart_HTML5_Canvas/blob/master/README.md
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: any
